import React from 'react';
import { useLanguageStore } from '../store/useLanguageStore';

export const AlgorithmExplanation: React.FC = () => {
  const { t, language } = useLanguageStore();

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', maxWidth: '1000px', margin: '0 auto' }}>
      {/* Title Header */}
      <div>
        <h1 style={{ fontSize: '1.8rem', fontWeight: 700, marginBottom: '6px' }}>
          {language === 'id' ? 'Sistem Algoritma Analisis BTST' : 'BTST Analysis Algorithm System'}
        </h1>
        <p style={{ color: '#94a3b8', fontSize: '0.9rem' }}>
          {language === 'id' 
            ? 'Penjelasan mendalam rumus matematika, bobot teknikal, dan alur penyaringan sistem Buy Today, Sell Tomorrow (BTST).' 
            : 'An in-depth explanation of the mathematical formulas, technical weights, and scanning workflow of the Buy Today, Sell Tomorrow (BTST) system.'}
        </p>
      </div>

      {/* Intro Card */}
      <div className="glass-panel" style={{ padding: '24px', lineHeight: 1.6 }}>
        <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: '#3b82f6', marginBottom: '12px' }}>
          {language === 'id' ? 'Apa itu Strategi BTST?' : 'What is the BTST Strategy?'}
        </h3>
        <p style={{ color: '#cbd5e1', fontSize: '0.92rem' }}>
          {language === 'id'
            ? 'Buy Today, Sell Tomorrow (BTST) adalah strategi perdagangan jangka pendek di mana trader membeli saham menjelang penutupan pasar saat mendeteksi akumulasi breakout yang kuat, dan menjualnya pada keesokan harinya saat pembukaan pasar untuk memanfaatkan celah harga (gap-up) akibat sisa momentum hari sebelumnya.'
            : 'Buy Today, Sell Tomorrow (BTST) is a short-term trading strategy where traders acquire shares near market close when strong breakout accumulation is detected, and sell them the following morning at market open to capitalize on price gaps (gap-ups) generated by residual momentum.'}
        </p>
      </div>

      {/* Formula & Weighting Card */}
      <div className="glass-panel" style={{ padding: '24px' }}>
        <h3 style={{ fontSize: '1.2rem', fontWeight: 600, marginBottom: '16px' }}>
          {language === 'id' ? 'Formulasi Skor BTST (Maksimal: 100)' : 'BTST Score Formulation (Max: 100)'}
        </h3>
        <div style={{
          backgroundColor: 'rgba(0, 0, 0, 0.3)',
          padding: '16px 20px',
          borderRadius: '8px',
          border: '1px solid rgba(255, 255, 255, 0.05)',
          fontFamily: 'monospace',
          fontSize: '0.95rem',
          color: '#06b6d4',
          marginBottom: '20px',
          textAlign: 'center',
          fontWeight: 'bold'
        }}>
          Skor = (RSI * 0.25) + (MACD * 0.30) + (EMA * 0.20) + (Vol * 0.15) + (BB * 0.10)
        </div>

        <p style={{ color: '#94a3b8', fontSize: '0.88rem', lineHeight: 1.5, marginBottom: '24px' }}>
          {language === 'id'
            ? 'Setiap parameter dievaluasi secara matematis oleh sistem di backend untuk menghasilkan nilai skor antara 0 hingga 100. Saham dengan skor di atas 70 dikategorikan memiliki momentum breakout kuat yang terverifikasi.'
            : 'Each parameter is mathematically evaluated by the backend engine to output a score between 0 and 100. Stocks scoring above 70 are categorized as verified high-momentum breakout candidates.'}
        </p>

        {/* 5 Points Breakdowns */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          
          {/* Factor 1 */}
          <div style={{ display: 'flex', gap: '16px', borderBottom: '1px solid rgba(255,255,255,0.04)', paddingBottom: '16px' }}>
            <div style={{
              width: '50px',
              height: '50px',
              borderRadius: '8px',
              backgroundColor: 'rgba(59, 130, 246, 0.1)',
              color: '#3b82f6',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontWeight: 700,
              fontSize: '1.1rem'
            }}>25%</div>
            <div style={{ flex: 1 }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#f8fafc', marginBottom: '4px' }}>
                Relative Strength Index (RSI - 14)
              </h4>
              <p style={{ color: '#cbd5e1', fontSize: '0.88rem', lineHeight: 1.5 }}>
                {language === 'id'
                  ? 'Mengukur kekuatan momentum perubahan harga. Sistem memberikan nilai tertinggi (Skor 90) jika RSI berada di rentang ideal 40-65 (momentum menanjak tanpa risiko overbought jenuh beli). RSI > 75 diberi skor rendah (30) karena risiko pullback.'
                  : 'Measures momentum strength. The engine awards the maximum rating (Score 90) if the RSI falls in the ideal 40-65 zone (accelerating momentum without overbought risks). RSI > 75 is penalized (Score 30) due to overextended pullback risks.'}
              </p>
            </div>
          </div>

          {/* Factor 2 */}
          <div style={{ display: 'flex', gap: '16px', borderBottom: '1px solid rgba(255,255,255,0.04)', paddingBottom: '16px' }}>
            <div style={{
              width: '50px',
              height: '50px',
              borderRadius: '8px',
              backgroundColor: 'rgba(16, 185, 129, 0.1)',
              color: '#10b981',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontWeight: 700,
              fontSize: '1.1rem'
            }}>30%</div>
            <div style={{ flex: 1 }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#f8fafc', marginBottom: '4px' }}>
                Moving Average Convergence Divergence (MACD 12, 26, 9)
              </h4>
              <p style={{ color: '#cbd5e1', fontSize: '0.88rem', lineHeight: 1.5 }}>
                {language === 'id'
                  ? 'Indikator tren dan momentum utama (bobot terbesar). Sistem mendeteksi arah histogram MACD. Jika histogram positif dan melebar (> 0), sistem memberikan skor optimal (95) yang mengonfirmasi adanya persilangan bullish.'
                  : 'Primary trend and momentum indicator (highest weight). The engine tracks the MACD histogram. Positive expanding histograms (> 0) indicating a recent bullish crossover get the maximum rating (Score 95).'}
              </p>
            </div>
          </div>

          {/* Factor 3 */}
          <div style={{ display: 'flex', gap: '16px', borderBottom: '1px solid rgba(255,255,255,0.04)', paddingBottom: '16px' }}>
            <div style={{
              width: '50px',
              height: '50px',
              borderRadius: '8px',
              backgroundColor: 'rgba(168, 85, 247, 0.1)',
              color: '#a855f7',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontWeight: 700,
              fontSize: '1.1rem'
            }}>20%</div>
            <div style={{ flex: 1 }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#f8fafc', marginBottom: '4px' }}>
                Exponential Moving Average (EMA 9, 21, 50)
              </h4>
              <p style={{ color: '#cbd5e1', fontSize: '0.88rem', lineHeight: 1.5 }}>
                {language === 'id'
                  ? 'Menilai konfigurasi tren harga. Sistem mensyaratkan harga berada di atas EMA9, EMA21, dan EMA50 secara berurutan (Golden Bullish Alignment). Jika terpenuhi, saham diberi nilai tren optimal 95.'
                  : 'Assesses trend structural alignment. The engine requires the price to stand above the EMA9, EMA21, and EMA50 simultaneously in a stacked layout (Golden Bullish Alignment), awarding an optimal rating of 95.'}
              </p>
            </div>
          </div>

          {/* Factor 4 */}
          <div style={{ display: 'flex', gap: '16px', borderBottom: '1px solid rgba(255,255,255,0.04)', paddingBottom: '16px' }}>
            <div style={{
              width: '50px',
              height: '50px',
              borderRadius: '8px',
              backgroundColor: 'rgba(236, 72, 153, 0.1)',
              color: '#ec4899',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontWeight: 700,
              fontSize: '1.1rem'
            }}>15%</div>
            <div style={{ flex: 1 }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#f8fafc', marginBottom: '4px' }}>
                Volume Confirmation Engine
              </h4>
              <p style={{ color: '#cbd5e1', fontSize: '0.88rem', lineHeight: 1.5 }}>
                {language === 'id'
                  ? 'Volume adalah bensin dari breakout. Algoritma membandingkan volume perdagangan hari ini dengan rata-rata volume 5 hari sebelumnya. Jika volume hari ini > 1.5x rata-rata 5 hari, sistem memberikan nilai penuh 95 sebagai konfirmasi breakout kuat.'
                  : 'Volume represents the fuel of a breakout. The algorithm compares today\'s volume against the prior 5-day average volume. If today\'s volume exceeds 1.5x the average, it secures a full rating of 95 verifying high liquidity interest.'}
              </p>
            </div>
          </div>

          {/* Factor 5 */}
          <div style={{ display: 'flex', gap: '16px' }}>
            <div style={{
              width: '50px',
              height: '50px',
              borderRadius: '8px',
              backgroundColor: 'rgba(6, 182, 212, 0.1)',
              color: '#06b6d4',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontWeight: 700,
              fontSize: '1.1rem'
            }}>10%</div>
            <div style={{ flex: 1 }}>
              <h4 style={{ fontSize: '1rem', fontWeight: 600, color: '#f8fafc', marginBottom: '4px' }}>
                Bollinger Bands Position (20, 2)
              </h4>
              <p style={{ color: '#cbd5e1', fontSize: '0.88rem', lineHeight: 1.5 }}>
                {language === 'id'
                  ? 'Menilai volatilitas dan rentang harga relatif. Sistem memindai posisi harga terhadap pita atas dan bawah. Posisi harga yang menempel di pita atas (> 85% area) menunjukkan trend-riding kuat (skor 80), sedangkan pantulan di pita bawah (< 15% area) menunjukkan potensi pembalikan arah support (skor 85).'
                  : 'Evaluates relative price boundaries and volatility. The system calculates where the current price stands inside the Bands. Values touching the Upper Band (> 85% range) imply a strong trend run (Score 80), while bounces off the Lower Band (< 15% range) target support reversals (Score 85).'}
              </p>
            </div>
          </div>

        </div>
      </div>

      {/* NEW: MACD Signals & Interpretation Card */}
      <div className="glass-panel" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
        <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: '#10b981' }}>
          {language === 'id' ? '📈 Cara Membaca & Interpretasi Sinyal MACD' : '📈 How to Read & Interpret MACD Signals'}
        </h3>
        <p style={{ color: '#cbd5e1', fontSize: '0.92rem', lineHeight: 1.6 }}>
          {language === 'id'
            ? 'MACD menghasilkan sinyal perdagangan melalui interaksi antara tiga komponen utama: Garis MACD, Garis Sinyal, dan Histogram. Berikut adalah tiga sinyal MACD utama yang dievaluasi secara otomatis oleh sistem kami:'
            : 'The MACD generates trading signals through the interaction of its three core components: the MACD Line, the Signal Line, and the Histogram. Here are the three primary MACD signals automatically evaluated by our scoring system:'}
        </p>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px', marginTop: '8px' }}>
          {/* Crossover Bullish */}
          <div style={{ padding: '16px', borderRadius: '8px', backgroundColor: 'rgba(16, 185, 129, 0.03)', border: '1px solid rgba(16, 185, 129, 0.15)' }}>
            <h4 style={{ fontWeight: 600, color: '#10b981', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <span>🟢</span> {language === 'id' ? 'Bullish Crossover (Beli)' : 'Bullish Crossover (Buy)'}
            </h4>
            <p style={{ fontSize: '0.85rem', lineHeight: 1.5, color: '#94a3b8' }}>
              {language === 'id'
                ? 'Terjadi ketika Garis MACD memotong ke atas Garis Sinyal. Ini menunjukkan momentum jangka pendek beralih menjadi jauh lebih kuat dibanding jangka panjang. Pada algoritma BTST kami, kondisi crossover positif ini otomatis memicu skor MACD maksimal (95).'
                : 'Occurs when the MACD Line crosses above the Signal Line. This indicates that short-term momentum is accelerating faster than the long-term trend. In our BTST algorithm, this positive crossover automatically triggers a near-maximum MACD rating (Score 95).'}
            </p>
          </div>

          {/* Histogram Expansion */}
          <div style={{ padding: '16px', borderRadius: '8px', backgroundColor: 'rgba(6, 182, 212, 0.03)', border: '1px solid rgba(6, 182, 212, 0.15)' }}>
            <h4 style={{ fontWeight: 600, color: '#06b6d4', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <span>📊</span> {language === 'id' ? 'Ekspansi Histogram (Akselerasi)' : 'Histogram Expansion (Acceleration)'}
            </h4>
            <p style={{ fontSize: '0.85rem', lineHeight: 1.5, color: '#94a3b8' }}>
              {language === 'id'
                ? 'Histogram mengukur jarak antara Garis MACD dan Garis Sinyal. Ketika histogram berwarna hijau dan melebar ke atas (> 0), ini mengonfirmasi bahwa tren penguatan sedang berakselerasi dengan sangat solid, ideal untuk strategi beli sore (BTST).'
                : 'The histogram measures the distance between the MACD Line and the Signal Line. When the histogram bars are green and expanding upwards (> 0), it confirms that the upward buying pressure is actively accelerating, which is ideal for BTST.'}
            </p>
          </div>

          {/* Bearish Crossover */}
          <div style={{ padding: '16px', borderRadius: '8px', backgroundColor: 'rgba(239, 68, 68, 0.03)', border: '1px solid rgba(239, 68, 68, 0.15)' }}>
            <h4 style={{ fontWeight: 600, color: '#ef4444', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <span>🔴</span> {language === 'id' ? 'Bearish Crossover (Hindari/Jual)' : 'Bearish Crossover (Avoid/Sell)'}
            </h4>
            <p style={{ fontSize: '0.85rem', lineHeight: 1.5, color: '#94a3b8' }}>
              {language === 'id'
                ? 'Terjadi ketika Garis MACD memotong ke bawah Garis Sinyal. Ini menandakan penurunan momentum dan awal dari tren melemah. Saham dengan kondisi bearish crossover atau histogram di bawah nol (< 0) akan diberi skor rendah (30) dan disaring keluar.'
                : 'Occurs when the MACD Line crosses below the Signal Line. This indicates a contraction in momentum and the start of a downtrend. Stocks exhibiting a bearish crossover or histogram below zero (< 0) are penalized (Score 30) and filtered out.'}
            </p>
          </div>
        </div>
      </div>

      {/* Authoritative Reference Section */}
      <div className="glass-panel" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
        <h3 style={{ fontSize: '1.2rem', fontWeight: 600, color: '#3b82f6' }}>
          {language === 'id' ? '📚 Referensi Teori Akademik & Indikator Teknis' : '📚 Academic Theory & Technical Indicator References'}
        </h3>
        
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', fontSize: '0.9rem', lineHeight: 1.6, color: '#cbd5e1' }}>
          
          {/* RSI Reference */}
          <div style={{ padding: '16px', borderRadius: '8px', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.04)' }}>
            <h4 style={{ fontWeight: 600, color: '#f8fafc', marginBottom: '8px' }}>
              1. Relative Strength Index (RSI)
            </h4>
            <p style={{ marginBottom: '10px' }}>
              {language === 'id'
                ? 'RSI pertama kali dikembangkan oleh J. Welles Wilder Jr. pada tahun 1978 di dalam bukunya yang terkenal, "New Concepts in Technical Trading Systems". Indikator osilator ini membandingkan ukuran keuntungan rata-rata dengan kerugian rata-rata selama 14 periode.'
                : 'The RSI was developed by J. Welles Wilder Jr. in 1978 and published in his seminal book, "New Concepts in Technical Trading Systems". This momentum oscillator compares the magnitude of recent gains to recent losses over 14 periods.'}
            </p>
            <div style={{ fontFamily: 'monospace', fontSize: '0.82rem', color: '#06b6d4', padding: '8px', backgroundColor: 'rgba(0,0,0,0.2)', borderRadius: '4px', marginBottom: '10px' }}>
              Formula: RSI = 100 - (100 / (1 + RS)) di mana RS = (Rata-rata Kenaikan / Rata-rata Penurunan)
            </div>
            <span style={{ fontSize: '0.78rem', color: '#94a3b8' }}>
              Ref: <a href="https://www.investopedia.com/terms/r/rsi.asp" target="_blank" rel="noopener noreferrer" style={{ color: '#3b82f6', textDecoration: 'none' }}>Investopedia RSI Article</a> | Wilder, J. W. (1978). *New Concepts in Technical Trading Systems*.
            </span>
          </div>

          {/* MACD Reference */}
          <div style={{ padding: '16px', borderRadius: '8px', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.04)' }}>
            <h4 style={{ fontWeight: 600, color: '#f8fafc', marginBottom: '8px' }}>
              2. Moving Average Convergence Divergence (MACD)
            </h4>
            <p style={{ marginBottom: '10px' }}>
              {language === 'id'
                ? 'MACD diciptakan oleh Gerald Appel pada akhir tahun 1970-an. Indikator ini sangat andal untuk mengidentifikasi momentum tren jangka pendek dan arah pergerakan harga dengan membandingkan hubungan antara dua rata-rata bergerak eksponensial (EMA).'
                : 'MACD was created by Gerald Appel in the late 1970s. It serves as an incredibly robust trend-following momentum indicator that reveals the relationship between two exponential moving averages (EMAs) of a security\'s price.'}
            </p>
            <div style={{ fontFamily: 'monospace', fontSize: '0.82rem', color: '#06b6d4', padding: '8px', backgroundColor: 'rgba(0,0,0,0.2)', borderRadius: '4px', marginBottom: '10px' }}>
              Formula: MACD Line = EMA12 - EMA26 | Signal Line = EMA9 dari MACD Line | Histogram = MACD Line - Signal Line
            </div>
            <span style={{ fontSize: '0.78rem', color: '#94a3b8' }}>
              Ref: <a href="https://www.investopedia.com/terms/m/macd.asp" target="_blank" rel="noopener noreferrer" style={{ color: '#3b82f6', textDecoration: 'none' }}>Investopedia MACD Article</a> | Appel, G. (2005). *Technical Analysis: Power Tools for Active Investors*.
            </span>
          </div>

          {/* EMA Reference */}
          <div style={{ padding: '16px', borderRadius: '8px', backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.04)' }}>
            <h4 style={{ fontWeight: 600, color: '#f8fafc', marginBottom: '8px' }}>
              3. Exponential Moving Average (EMA)
            </h4>
            <p style={{ marginBottom: '10px' }}>
              {language === 'id'
                ? 'Rata-rata Bergerak Eksponensial (EMA) adalah salah satu alat analisis tren fundamental dalam teori investasi modern. Berbeda dengan Simple Moving Average (SMA), EMA memberikan bobot yang lebih besar pada harga penutupan terbaru sehingga mendeteksi tren berbalik jauh lebih cepat.'
                : 'The Exponential Moving Average (EMA) is a fundamental trend-following indicator in modern trading theory. Unlike a Simple Moving Average (SMA), an EMA applies more weight to recent price data, making it highly sensitive to recent price shifts.'}
            </p>
            <div style={{ fontFamily: 'monospace', fontSize: '0.82rem', color: '#06b6d4', padding: '8px', backgroundColor: 'rgba(0,0,0,0.2)', borderRadius: '4px', marginBottom: '10px' }}>
              Formula: EMA(t) = (Harga(t) * (Multiplier / (1 + Period))) + EMA(t-1) * (1 - (Multiplier / (1 + Period)))
            </div>
            <span style={{ fontSize: '0.78rem', color: '#94a3b8' }}>
              Ref: <a href="https://www.investopedia.com/terms/e/ema.asp" target="_blank" rel="noopener noreferrer" style={{ color: '#3b82f6', textDecoration: 'none' }}>Investopedia EMA Article</a> | Murphy, J. J. (1999). *Technical Analysis of the Financial Markets*.
            </span>
          </div>

        </div>
      </div>

      {/* Safety Alert Disclaimer */}
      <div className="glass-panel" style={{
        padding: '20px',
        borderLeft: '4px solid #f59e0b',
        backgroundColor: 'rgba(245, 158, 11, 0.02)',
        fontSize: '0.88rem',
        lineHeight: 1.6,
        color: '#cbd5e1'
      }}>
        <strong>{language === 'id' ? '⚠️ Manajemen Risiko BTST:' : '⚠️ BTST Risk Management:'}</strong>
        <br />
        {language === 'id'
          ? 'Meskipun skor algoritma di atas 70 mengindikasikan probabilitas tinggi kenaikan keesokan harinya, pastikan Anda menggunakan stop loss ketat sebesar 2-3% untuk memitigasi jika pasar tiba-tiba berbalik arah akibat berita global (gap-down).'
          : 'Although algorithm scores exceeding 70 point to a high probability of morning gap-ups, always employ a disciplined 2-3% stop loss to protect capital in the event of global market reversals or unexpected morning gap-downs.'}
      </div>
    </div>
  );
};

export default AlgorithmExplanation;
